#!/bin/sh
if [ -n "$1" ]; then
	TOP="$1"
else
	cd `dirname $0`/../..
	TOP="`pwd`"
fi
echo "Running in $TOP" >/tmp/sucking
if ! [ -d "$TOP"/bionic/libc ]; then
	echo "Usage: $0 /path/to/Android/source" >/dev/stderr
	exit 1
fi
if ! [ -d "$TOP"/kernel ]; then
	echo "No kernel found in $1/kernel" >/dev/stderr
	exit 0
fi
echo "Actually running" >>/tmp/sucking
cd "$TOP/kernel"
make headers_install V=1 ARCH=arm INSTALL_HDR_PATH="$TOP"/external/kernel-headers/current &>>/tmp/sucking
# Some files commonly not marked as exporting public bits...
for i in include/video/*; do
	[ -f $i ] || continue
	[ -e "$TOP"/external/kernel-headers/current/$i ] || cp -f $i "$TOP"/external/kernel-headers/current/$i
done
"$TOP/bionic/libc/kernel/tools/update_all.py" "$TOP/external/kernel-headers/current/include" &>>/tmp/sucking
